server:
  port: 8082

spring:
  application:
    name: users-service

  datasource:
    url: jdbc:mariadb://localhost:3306/shop_users
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

  # Flyway 설정
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# Eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# JWT 설정
jwt:
  secret: ${JWT_SECRET:bWV5QnVkZGluZ1NlY3JldEtleUZvckpXVFNlcnZpY2U=}
  expiration: 86400000      # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)

# 다른 서비스 연동 설정
posts-service:
  url: ${POSTS_SERVICE_URL:http://localhost:8081}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
    git:
      mode: full

# 로깅 설정
logging:
  level:
    com.berryweb.shop.users: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/users-service.log

# OpenFeign 설정
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
  hystrix:
    enabled: false

# 스프링 부트 정보
info:
  app:
    name: Users Service
    description: MSA 기반 사용자 관리 서비스
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17

# 프로파일별 설정
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/shop_users
    username: root
    password: admin
logging:
  level:
    root: INFO
    com.berryweb.shop.users: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://dev-db:3306/shop_users
    username: ${DB_USERNAME:shop_user}
    password: ${DB_PASSWORD:shop_password}
logging:
  level:
    root: INFO
    com.berryweb.shop.users: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${DB_HOST:prod-db}:${DB_PORT:3306}/${DB_NAME:shop_users}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
logging:
  level:
    root: WARN
    com.berryweb.shop.users: INFO